version: "3.3"
services:
  tailwind:
    build: .
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/workspace
      - tailwind_node_modules:/workspace/node_modules
    tty: true
    stdin_open: true

volumes:
  tailwind_node_modules:
